INFO 2023-05-19 00:40:00,758 [root:config.py:<module>:86]
Informative messages from your code.

WARNING 2023-05-19 00:40:00,758 [root:config.py:<module>:87]
Everything works but there is something to be aware of.

ERROR 2023-05-19 00:40:00,769 [root:config.py:<module>:88]
There's been a mistake with the process.

CRITICAL 2023-05-19 00:40:00,770 [root:config.py:<module>:89]
There is something terribly wrong and process may terminate.

INFO 2023-05-19 20:37:31,507 [root:config.py:<module>:89]
Informative messages from your code.

WARNING 2023-05-19 20:37:31,512 [root:config.py:<module>:90]
Everything works but there is something to be aware of.

ERROR 2023-05-19 20:37:31,513 [root:config.py:<module>:91]
There's been a mistake with the process.

CRITICAL 2023-05-19 20:37:31,515 [root:config.py:<module>:92]
There is something terribly wrong and process may terminate.

INFO 2023-05-21 11:08:42,202 [uvicorn.error:server.py:serve:75]
Started server process [3312]

INFO 2023-05-21 11:08:42,220 [uvicorn.error:on.py:startup:45]
Waiting for application startup.

ERROR 2023-05-21 11:08:42,243 [uvicorn.error:on.py:send:119]
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\Grind\MLOPS\mlops\.\app\api.py", line 27, in load_artifacts
    run_id = open(Path(config.CONFIG_DIR, "run_id.txt")).read()
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Grind\\MLOPS\\mlops\\Config\\run_id.txt'


ERROR 2023-05-21 11:08:42,291 [uvicorn.error:on.py:startup:56]
Application startup failed. Exiting.

INFO 2023-05-21 11:08:57,839 [uvicorn.error:server.py:serve:75]
Started server process [24572]

INFO 2023-05-21 11:08:57,855 [uvicorn.error:on.py:startup:45]
Waiting for application startup.

ERROR 2023-05-21 11:08:57,863 [uvicorn.error:on.py:send:119]
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\Grind\MLOPS\mlops\.\app\api.py", line 27, in load_artifacts
    run_id = open(Path(config.CONFIG_DIR, "run_id.txt")).read()
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Grind\\MLOPS\\mlops\\Config\\run_id.txt'


ERROR 2023-05-21 11:08:57,903 [uvicorn.error:on.py:startup:56]
Application startup failed. Exiting.

INFO 2023-05-21 11:09:21,203 [uvicorn.error:server.py:serve:75]
Started server process [23460]

INFO 2023-05-21 11:09:21,217 [uvicorn.error:on.py:startup:45]
Waiting for application startup.

ERROR 2023-05-21 11:09:21,217 [uvicorn.error:on.py:send:119]
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\Grind\MLOPS\mlops\.\app\api.py", line 27, in load_artifacts
    run_id = open(Path(config.CONFIG_DIR, "run_id.txt")).read()
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Grind\\MLOPS\\mlops\\Config\\run_id.txt'


ERROR 2023-05-21 11:09:21,249 [uvicorn.error:on.py:startup:56]
Application startup failed. Exiting.

INFO 2023-05-21 11:10:04,412 [uvicorn.error:server.py:serve:75]
Started server process [20112]

INFO 2023-05-21 11:10:04,436 [uvicorn.error:on.py:startup:45]
Waiting for application startup.

INFO 2023-05-21 11:10:04,444 [uvicorn.error:on.py:startup:59]
Application startup complete.

INFO 2023-05-21 11:40:08,791 [uvicorn.error:server.py:serve:75]
Started server process [21304]

INFO 2023-05-21 11:40:08,810 [uvicorn.error:on.py:startup:45]
Waiting for application startup.

INFO 2023-05-21 11:40:08,818 [uvicorn.error:on.py:startup:59]
Application startup complete.

